// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRvTwVu9DfWsOtvm8sVRsOZZEWhapotDg',
    appId: '1:976230002574:web:27f5a7420c1d1dfa707edf',
    messagingSenderId: '976230002574',
    projectId: 'gestion-de-residuos-ec0a2',
    authDomain: 'gestion-de-residuos-ec0a2.firebaseapp.com',
    storageBucket: 'gestion-de-residuos-ec0a2.firebasestorage.app',
    measurementId: 'G-XBYV26Z77M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBO2IATVQzFQSf8Uq6MiU_v1Dua-yPFM',
    appId: '1:976230002574:android:f766748778e3f188707edf',
    messagingSenderId: '976230002574',
    projectId: 'gestion-de-residuos-ec0a2',
    storageBucket: 'gestion-de-residuos-ec0a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxMluJV5jS12fuu6rmQnIbk0tVr1dep68',
    appId: '1:976230002574:ios:0424d1258839b438707edf',
    messagingSenderId: '976230002574',
    projectId: 'gestion-de-residuos-ec0a2',
    storageBucket: 'gestion-de-residuos-ec0a2.firebasestorage.app',
    androidClientId: '976230002574-b0q7elov7c09omhur1c6m8qufpphka20.apps.googleusercontent.com',
    iosClientId: '976230002574-oo371fo2mva1gsf4kimcjorqvvq6jv5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePrueba2',
  );
}
